name: Release Pipeline

on:
  workflow_run:
    workflows: ["Build & Verify Pipeline"]
    branches: [main]
    types:
      - completed

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  semantic-release:
    name: Semantic Release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install semantic-release
        run: |
          npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run semantic-release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release

      - name: Extract version from git tag
        id: extract_version
        if: steps.semantic.outcome == 'success'
        run: |
          VERSION=$(git describe --tags --abbrev=0 --always)
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Released version: $VERSION"
          # Dynamically set the tag name for use in later steps
          TAG_NAME="v$VERSION"
          echo "tag_name=$TAG_NAME" >> $GITHUB_ENV

      - name: Validate Git Tag
        run: |
          TAG_NAME=${{ env.TAG_NAME }}
          EXISTING_TAG=$(git tag --points-at ${GITHUB_SHA})
          if [ "$EXISTING_TAG" != "$TAG_NAME" ]; then
            git tag -f $TAG_NAME ${GITHUB_SHA}
            git push origin $TAG_NAME --force
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'arm64,amd64,arm'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        if: steps.extract_version.outcome == 'success'
        with:
          version: v1.18.2
          distribution: goreleaser
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GORELEASER_CURRENT_TAG: v${{ steps.extract_version.outputs.version }}


  # GoReleaser handles the Docker image building and publishing

env:
  GO_VERSION: "1.24"
  REGISTRY: ghcr.io
